# updatebtw config module

UPDATERBTW_CONFIG="${UPDATERBTW_CONFIG:-/etc/updatebtw/updatebtw.conf}"
AUR_USER="${AUR_USER:-aur_builder}"

read_config() {
  [ -f "$UPDATERBTW_CONFIG" ] && . "$UPDATERBTW_CONFIG" || true
}

write_config() {
  local config_dir
  config_dir="$(dirname "$UPDATERBTW_CONFIG")"
  mkdir -p "$config_dir"
  cat > "$UPDATERBTW_CONFIG" << EOF
# updatebtw configuration
# Generated by updatebtw installer

AUR_HELPER="${AUR_HELPER:-yay}"
UPDATE_FREQUENCY="${UPDATE_FREQUENCY:-weekly}"
UPDATE_TIME="${UPDATE_TIME:-06:00}"
RUN_AT_BOOT="${RUN_AT_BOOT:-false}"
ENABLE_REFLECTOR="${ENABLE_REFLECTOR:-true}"
REFLECTOR_COUNTRY="${REFLECTOR_COUNTRY:-United States}"
REFLECTOR_PROTOCOL="${REFLECTOR_PROTOCOL:-https}"
REFLECTOR_INTERVAL="${REFLECTOR_INTERVAL:-30}"
SILENT_BOOT="${SILENT_BOOT:-false}"
AUR_USER="${AUR_USER:-aur_builder}"
EOF
}

validate_config() {
  local errors=""
  case "${AUR_HELPER:-yay}" in
    yay|paru) ;;
    *) errors="${errors}error: AUR_HELPER must be 'yay' or 'paru' (got: ${AUR_HELPER})\n" ;;
  esac
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily|weekly|monthly) ;;
    *) errors="${errors}error: UPDATE_FREQUENCY must be 'daily', 'weekly', or 'monthly' (got: ${UPDATE_FREQUENCY})\n" ;;
  esac
  if [ -n "$errors" ]; then
    printf '%b' "$errors" >&2
    return 1
  fi
  return 0
}

calendar_from_config() {
  local time="${UPDATE_TIME:-06:00}"
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily)   echo "*-*-* ${time}:00" ;;
    weekly)  echo "Mon *-*-* ${time}:00" ;;
    monthly) echo "*-*-01 ${time}:00" ;;
  esac
}
