# updatebtw config module

UPDATERBTW_CONFIG="${UPDATERBTW_CONFIG:-/etc/updatebtw/updatebtw.conf}"
AUR_USER="${AUR_USER:-aur_builder}"
FLATPAK_USER="${FLATPAK_USER:-${AUR_USER:-aur_builder}}"

_allowed_config_keys="AUR_HELPER UPDATE_FREQUENCY UPDATE_TIME RUN_AT_BOOT ENABLE_REFLECTOR REFLECTOR_COUNTRY REFLECTOR_PROTOCOL REFLECTOR_INTERVAL SILENT_BOOT AUR_USER FLATPAK_USER BLACKLIST_MODULES"

# Strict allowlist of characters permitted in config values.
# Covers: alphanumerics, _, ., /, space, :, @, comma, +, -
# Excludes: $ ` ; & | ( ) { } ! < > ' " [ ] \ ~ # % ^ * ?
_safe_value_pattern='^[a-zA-Z0-9_./ :@,+.-]*$'

_safe_read_config() {
  local cfg="$1"
  [ -f "$cfg" ] || return 0

  if [ -L "$cfg" ]; then
    echo "updatebtw: config $cfg is a symlink, refusing" >&2
    return 1
  fi

  local real_path
  real_path="$(readlink -f "$cfg" 2>/dev/null)" || return 1

  # Open fd FIRST — kernel holds reference to the inode from this point
  exec 8< "$cfg"

  # Validate via /proc/self/fd/8 to eliminate TOCTOU between stat and open
  # Use -L to follow the /proc/self/fd/N symlink to the actual file
  local perms owner
  perms="$(stat -L -c '%a' /proc/self/fd/8 2>/dev/null)" || { exec 8<&-; return 1; }
  if [ "$perms" != "600" ] && [ "$perms" != "400" ]; then
    echo "updatebtw: config has unsafe permissions ($perms), expected 600 or 400" >&2
    exec 8<&-
    return 1
  fi

  owner="$(stat -L -c '%U' /proc/self/fd/8 2>/dev/null)" || { exec 8<&-; return 1; }
  if [ "$owner" != "root" ]; then
    echo "updatebtw: config is not owned by root (owned by $owner)" >&2
    exec 8<&-
    return 1
  fi

  # Verify the opened fd resolves to the same inode we expected
  local fd_real_path
  fd_real_path="$(readlink -f /proc/self/fd/8 2>/dev/null)" || { exec 8<&-; return 1; }
  if [ "$fd_real_path" != "$real_path" ]; then
    echo "updatebtw: config file resolved to unexpected path, refusing" >&2
    exec 8<&-
    return 1
  fi

  local line key value
  while IFS= read -r line <&8; do
    case "$line" in
      ""|\#*) continue ;;
    esac
    key="${line%%=*}"
    key="$(printf '%s' "$key" | tr -d '[:space:]')"
    local allowed=false k
    for k in $_allowed_config_keys; do
      if [ "$key" = "$k" ]; then
        allowed=true
        break
      fi
    done
    if ! $allowed; then
      echo "updatebtw: config $cfg contains unknown key: $key" >&2
      exec 8<&-
      return 1
    fi

    # Extract value: strip key= and surrounding quotes
    value="${line#*=}"
    # Remove leading/trailing double quotes if present
    case "$value" in
      '"'*'"') value="$(printf '%s' "$value" | sed 's/^"//;s/"$//')" ;;
    esac

    # Strict character allowlist — no dangerous syntax can pass
    if ! printf '%s' "$value" | grep -qE "$_safe_value_pattern"; then
      echo "updatebtw: config $cfg contains invalid characters in: $line" >&2
      exec 8<&-
      return 1
    fi

    # Set variable directly — never source the file
    case "$key" in
      AUR_HELPER)        AUR_HELPER="$value" ;;
      UPDATE_FREQUENCY)  UPDATE_FREQUENCY="$value" ;;
      UPDATE_TIME)       UPDATE_TIME="$value" ;;
      RUN_AT_BOOT)       RUN_AT_BOOT="$value" ;;
      ENABLE_REFLECTOR)  ENABLE_REFLECTOR="$value" ;;
      REFLECTOR_COUNTRY) REFLECTOR_COUNTRY="$value" ;;
      REFLECTOR_PROTOCOL) REFLECTOR_PROTOCOL="$value" ;;
      REFLECTOR_INTERVAL) REFLECTOR_INTERVAL="$value" ;;
      SILENT_BOOT)       SILENT_BOOT="$value" ;;
      BLACKLIST_MODULES) BLACKLIST_MODULES="$value" ;;
      AUR_USER)          AUR_USER="$value" ;;
      FLATPAK_USER)      FLATPAK_USER="$value" ;;
    esac
  done

  exec 8<&-
}

read_config() {
  _safe_read_config "$UPDATERBTW_CONFIG"
}

write_config() {
  local config_dir
  config_dir="$(dirname "$UPDATERBTW_CONFIG")"
  mkdir -p "$config_dir"
  local default_flatpak_user="${SUDO_USER:-}"
  [ -z "$default_flatpak_user" ] && default_flatpak_user="$(id -un)"
  cat > "$UPDATERBTW_CONFIG" << EOF
# updatebtw configuration
# Generated by updatebtw installer

AUR_HELPER="${AUR_HELPER:-yay}"
UPDATE_FREQUENCY="${UPDATE_FREQUENCY:-weekly}"
UPDATE_TIME="${UPDATE_TIME:-06:00}"
RUN_AT_BOOT="${RUN_AT_BOOT:-false}"
ENABLE_REFLECTOR="${ENABLE_REFLECTOR:-true}"
REFLECTOR_COUNTRY="${REFLECTOR_COUNTRY:-United States}"
REFLECTOR_PROTOCOL="${REFLECTOR_PROTOCOL:-https}"
REFLECTOR_INTERVAL="${REFLECTOR_INTERVAL:-30}"
SILENT_BOOT="${SILENT_BOOT:-false}"
BLACKLIST_MODULES="${BLACKLIST_MODULES:-sp5100_tco}"
AUR_USER="${AUR_USER:-aur_builder}"
FLATPAK_USER="${FLATPAK_USER:-$default_flatpak_user}"
EOF
  chmod 600 "$UPDATERBTW_CONFIG"
  chown root:root "$UPDATERBTW_CONFIG" 2>/dev/null || true
}

validate_config() {
  local errors=""
  case "${AUR_HELPER:-yay}" in
    yay|paru) ;;
    *) errors="${errors}error: AUR_HELPER must be 'yay' or 'paru' (got: ${AUR_HELPER})\n" ;;
  esac
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily|weekly|monthly) ;;
    *) errors="${errors}error: UPDATE_FREQUENCY must be 'daily', 'weekly', or 'monthly' (got: ${UPDATE_FREQUENCY})\n" ;;
  esac
  if [ -n "$errors" ]; then
    printf '%b' "$errors" >&2
    return 1
  fi
  return 0
}

calendar_from_config() {
  local time="${UPDATE_TIME:-06:00}"
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily)   echo "*-*-* ${time}:00" ;;
    weekly)  echo "Mon *-*-* ${time}:00" ;;
    monthly) echo "*-*-01 ${time}:00" ;;
  esac
}
