# updatebtw config module

UPDATERBTW_CONFIG="${UPDATERBTW_CONFIG:-/etc/updatebtw/updatebtw.conf}"
AUR_USER="${AUR_USER:-aur_builder}"
FLATPAK_USER="${FLATPAK_USER:-${AUR_USER:-aur_builder}}"

_allowed_config_keys="AUR_HELPER UPDATE_FREQUENCY UPDATE_TIME RUN_AT_BOOT ENABLE_REFLECTOR REFLECTOR_COUNTRY REFLECTOR_PROTOCOL REFLECTOR_INTERVAL SILENT_BOOT AUR_USER FLATPAK_USER BLACKLIST_MODULES"

_safe_read_config() {
  local cfg="$1"
  [ -f "$cfg" ] || return 0

  local perms
  perms="$(stat -c '%a' "$cfg" 2>/dev/null)" || return 1
  if [ "$perms" != "600" ] && [ "$perms" != "400" ]; then
    echo "updatebtw: config $cfg has unsafe permissions ($perms), expected 600 or 400" >&2
    return 1
  fi

  local owner
  owner="$(stat -c '%U' "$cfg" 2>/dev/null)" || return 1
  if [ "$owner" != "root" ]; then
    echo "updatebtw: config $cfg is not owned by root (owned by $owner)" >&2
    return 1
  fi

  local line key
  while IFS= read -r line; do
    case "$line" in
      ""|\#*) continue ;;
    esac
    key="${line%%=*}"
    key="$(printf '%s' "$key" | tr -d '[:space:]')"
    local allowed=false k
    for k in $_allowed_config_keys; do
      if [ "$key" = "$k" ]; then
        allowed=true
        break
      fi
    done
    if ! $allowed; then
      echo "updatebtw: config $cfg contains unknown key: $key" >&2
      return 1
    fi
    case "$line" in
      *'$('*|*'`'*|*';'*|*'&'*|*'|'*)
        echo "updatebtw: config $cfg contains dangerous syntax in: $line" >&2
        return 1
        ;;
    esac
  done < "$cfg"

  . "$cfg"
}

read_config() {
  _safe_read_config "$UPDATERBTW_CONFIG"
}

write_config() {
  local config_dir
  config_dir="$(dirname "$UPDATERBTW_CONFIG")"
  mkdir -p "$config_dir"
  cat > "$UPDATERBTW_CONFIG" << EOF
# updatebtw configuration
# Generated by updatebtw installer

AUR_HELPER="${AUR_HELPER:-yay}"
UPDATE_FREQUENCY="${UPDATE_FREQUENCY:-weekly}"
UPDATE_TIME="${UPDATE_TIME:-06:00}"
RUN_AT_BOOT="${RUN_AT_BOOT:-false}"
ENABLE_REFLECTOR="${ENABLE_REFLECTOR:-true}"
REFLECTOR_COUNTRY="${REFLECTOR_COUNTRY:-United States}"
REFLECTOR_PROTOCOL="${REFLECTOR_PROTOCOL:-https}"
REFLECTOR_INTERVAL="${REFLECTOR_INTERVAL:-30}"
SILENT_BOOT="${SILENT_BOOT:-false}"
BLACKLIST_MODULES="${BLACKLIST_MODULES:-sp5100_tco}"
AUR_USER="${AUR_USER:-aur_builder}"
FLATPAK_USER="${FLATPAK_USER:-${SUDO_USER:-$(id -un)}}"
EOF
  chmod 600 "$UPDATERBTW_CONFIG"
  chown root:root "$UPDATERBTW_CONFIG" 2>/dev/null || true
}

validate_config() {
  local errors=""
  case "${AUR_HELPER:-yay}" in
    yay|paru) ;;
    *) errors="${errors}error: AUR_HELPER must be 'yay' or 'paru' (got: ${AUR_HELPER})\n" ;;
  esac
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily|weekly|monthly) ;;
    *) errors="${errors}error: UPDATE_FREQUENCY must be 'daily', 'weekly', or 'monthly' (got: ${UPDATE_FREQUENCY})\n" ;;
  esac
  if [ -n "$errors" ]; then
    printf '%b' "$errors" >&2
    return 1
  fi
  return 0
}

calendar_from_config() {
  local time="${UPDATE_TIME:-06:00}"
  case "${UPDATE_FREQUENCY:-weekly}" in
    daily)   echo "*-*-* ${time}:00" ;;
    weekly)  echo "Mon *-*-* ${time}:00" ;;
    monthly) echo "*-*-01 ${time}:00" ;;
  esac
}
